add apply_response_change to person
Mobile-AIMate/D-UI pull request #27
Opened 2023-08-01 18:12 UTC by ZQ-art

2023-08-02 02:50 UTC, kakaaaaa4 requested changes

2023-08-02 02:50 UTC, kakaaaaa4 commented on dui/llm.py
> +    pattern = r'{[^{}]*}'
提取回答输出的JSON识别代码段标志```应该会相对更精确

2023-08-02 02:50 UTC, kakaaaaa4 commented on dui/llm.py
> +    pattern = r'{[^{}]*}'
已有ResponseChange类，似乎不需要再定义函数？

2023-08-03 03:08 UTC, kakaaaaa4 requested changes

2023-08-03 03:08 UTC, kakaaaaa4 commented on tests/test_ResponseChange.py
>          '''
验证有效性与错误处理部分，需要检测JSON是否包含正确的5个键以及对应的值是否可用（即值的内容可以转化为数值而非文本内容）。当前处理方式不足以验证JSON正确性

2023-08-06 12:11 UTC, kakaaaaa4 requested changes

2023-08-06 12:11 UTC, kakaaaaa4 commented on tests/test_ResponseChange.py
> +                float(result[key])
判断是否是数字字符为什么要用float类型呢？

2023-08-07 04:55 UTC, kakaaaaa4 requested changes

2023-08-07 04:55 UTC, kakaaaaa4 commented on tests/test_ResponseChange.py
> +            self.assertTrue(isinstance(result[key], int), f"'{key}' is disabled")
考虑一下小数情况

2023-08-11 05:36 UTC, kakaaaaa4 approved these changes

2023-08-11 08:33 UTC, RedContritio requested changes

2023-08-11 08:33 UTC, RedContritio commented on dui/types/person.py
> +                    break
为什么 `break`，同时有两种 emotion 改变能正确运行吗？添加这样的单测

2023-08-22 06:54 UTC, RedContritio requested changes

2023-08-22 06:54 UTC, RedContritio commented on dui/llm.py
> +情绪的变化量为{happy: "+5", sad: "0", hate: "0", amazed: "0", angry: "0"}。\
为什么必须是字符串 "+5"，不能是数字 5 吗？

2023-08-22 06:54 UTC, RedContritio commented on dui/llm.py
> +if __name__ == "__main__":
这又是哪来的？记得 rebase

2023-08-22 06:54 UTC, RedContritio commented on dui/types/demand.py
> +    def set_emotion_hedging(self, x: Decimal):
为啥叫 set_XXX？它修改了 self 吗？下面逻辑是否过分冗余了？

2023-08-22 06:54 UTC, RedContritio commented on dui/types/person.py
> +EMOTION_NAMES_CN = ['开心', '难过', '讨厌', '惊讶', '生气']
为啥要重定义而不 `import`？

2023-08-22 06:54 UTC, RedContritio commented on dui/types/person.py
> +if __name__ == '__main__':
同上，先 rebase 再说

2023-08-22 08:11 UTC, RedContritio requested changes

2023-08-22 08:11 UTC, RedContritio commented on dui/types/demand.py
> +    def emotion_hedging(self, x: Decimal):
能否更简单？这个逻辑看起来还是很复杂，以及它为什么需要一个输入？

2023-08-22 08:11 UTC, RedContritio commented on tests/test_PersonEmotionChange.py
> +EMOTION_NAMES_CN = ['开心', '难过', '讨厌', '惊讶', '生气']
这儿有单独定义的原因吗

2023-08-22 08:11 UTC, RedContritio commented on tests/test_emotionHedging.py
> +EMOTION_NAMES_CN = ['开心', '难过', '讨厌', '惊讶', '生气']
同上

2023-08-22 13:45 UTC, RedContritio approved these changes

2023-08-22 14:05 UTC, kakaaaaa4 approved these changes

2023-08-23 03:14 UTC, merged