add intensity in Emotion
Mobile-AIMate/D-UI pull request #28
Opened 2023-08-11 09:38 UTC by DzhiWang

### Description

add intensity in Emotion & test

2023-08-11 17:30 UTC, RedContritio requested changes

2023-08-11 17:30 UTC, RedContritio commented on dui/types/demand.py
> +    def intensity(self):
举个例子，300 + 400 应该比 300 + 450 的结果小，但该写法不能区分两者。
因此需要改用其他方法进行强度计算，并且添加这样的单测

2023-08-12 05:33 UTC, RedContritio requested changes

2023-08-12 05:33 UTC, RedContritio commented on dui/types/demand.py
> +        return sum(self._value[1:]) / 5
这里是平均值方案，但是这样会导致，[10, 90] 和 [50, 50] 一样大，按照需求，前者应该大于后者

2023-08-14 08:11 UTC, RedContritio requested changes

2023-08-14 08:11 UTC, RedContritio commented on dui/types/demand.py
> +            (1 + prod / pow(max_component, len(self._value) - 1))
分母的底数是其数值上限，而不是 `max(value)`， 单独设置变量来表示

2023-08-14 08:17 UTC, DzhiWang commented on dui/types/demand.py
> +            (1 + prod / pow(max_component, len(self._value) - 1))
500吗

2023-08-14 08:42 UTC, RedContritio commented on dui/types/demand.py
> +            (1 + prod / pow(max_component, len(self._value) - 1))
把最大值 （500） 配置到 Emotion 类里

2023-08-18 10:52 UTC, RedContritio approved these changes

2023-08-18 10:52 UTC, merged