add 'Calculate the difference between its current emotion and the stable point'
Mobile-AIMate/D-UI pull request #29
Opened 2023-08-11 09:59 UTC by DzhiWang

### Description

add 'Calculate the difference between its current emotion and the stable point'

2023-08-11 17:33 UTC, RedContritio requested changes

2023-08-11 17:33 UTC, RedContritio commented on dui/types/demand.py
> +    @property
这个是否和 #28 重复了？检查一下重复部分

2023-08-11 17:33 UTC, RedContritio commented on dui/types/person.py
> +    def emotion_dif(self) -> list:
是否不需要手动逐项做差？因为 `DecimalList` 能支持做差；

此外将方法名称改成 `emotion_offset` 吧，并添加 `@property`。

2023-08-12 05:31 UTC, RedContritio requested changes

2023-08-12 05:31 UTC, RedContritio commented on tests/test_emotion.py
> +class Testintensity(unittest.TestCase):
这个单测过不了

2023-08-14 07:50 UTC, RedContritio requested changes

2023-08-14 07:50 UTC, RedContritio commented on dui/types/person.py
> +    def emotion_offset(self) -> list:
为什么是 `list` 不是 `DecimalList`

2023-08-14 08:18 UTC, DzhiWang commented on dui/types/person.py
> +    def emotion_offset(self) -> list:
嗷嗷，正常应该是DecimalList，需要返回Emotion吗？

2023-08-14 08:41 UTC, RedContritio commented on dui/types/person.py
> +    def emotion_offset(self) -> list:
不需要，你按照自己的理解返回就行

2023-08-18 10:53 UTC, RedContritio commented
解决一下冲突

2023-08-18 10:54 UTC, RedContritio approved these changes

2023-08-19 11:52 UTC, merged