修改extract_from_excel默认读取的文件；修改输出历史数据的格式为yml
Mobile-AIMate/D-UI pull request #55
Opened 2023-09-12 13:38 UTC by 1099255210

### Description
使extract_from_excel支持直接 python utils/extract_from_excel.py（目前通过type ignore）；修改extract_from_excel默认读取的文件为data/origin.xlsx；修改输出历史数据的格式为yml（保留输出json的代码，通过判断输出文件名实现不同的输出）

2023-09-12 14:01 UTC, RedContritio commented
追加：
- [ ] 移除当前 `example` 目录
- [ ] 添加输出结果至 `data/`

2023-09-12 14:26 UTC, 1099255210 commented
> 追加：
> 
>     * [ ]  移除当前 `example` 目录
> 
>     * [ ]  添加输出结果至 `data/`

需要我移除example目录吗？

2023-09-13 05:26 UTC, RedContritio commented
> > 追加：
> > ```
> > * [ ]  移除当前 `example` 目录
> > 
> > * [ ]  添加输出结果至 `data/`
> > ```
> 
> 需要我移除example目录吗？

需要

2023-09-15 14:29 UTC, RedContritio commented
1. 对引入的包需要添加 requirements：`pandas`
2. 当前运行会发生错误，建议自行测试：
```bash
Traceback (most recent call last):
  File "/D-UI/utils/extract_from_excel.py", line 17, in <module>
    with open(r"./example/example.json", 'r', encoding='utf-8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './example/example.json'
```

2023-09-15 14:46 UTC, 1099255210 commented
> 1. 对引入的包需要添加 requirements：`pandas`
> 
>     2. 当前运行会发生错误，建议自行测试：
> 
> 
> ```shell
> Traceback (most recent call last):
>   File "/D-UI/utils/extract_from_excel.py", line 17, in <module>
>     with open(r"./example/example.json", 'r', encoding='utf-8') as json_file:
> FileNotFoundError: [Errno 2] No such file or directory: './example/example.json'
> ```

请运行 `extract_from_excel_v2.py` 新的读取代码在这个里面

2023-09-15 14:49 UTC, RedContritio requested changes

2023-09-15 14:49 UTC, RedContritio commented on utils/extract_from_excel.py
>  with open(r"./example/example.json", 'r', encoding='utf-8') as json_file:
思索，但是你这儿还是试图找这个刚删掉的文件？

2023-09-15 14:49 UTC, RedContritio commented on utils/extract_from_excel.py
>      file: str = './example/example_dirty.xlsx',
+1

2023-10-11 13:31 UTC, RedContritio commented
解决冲突

2023-10-14 12:52 UTC, RedContritio approved these changes
LGTM

2023-10-14 12:52 UTC, merged